---
- name: Install wireguard server
  hosts: vpn_server

  tasks:
    - name: Install wireguard
      ansible.builtin.include_tasks: shared.yml

    - name: Wireguard config
      become: true
      ansible.builtin.template:
        src: templates/server.wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: "0600"

    - name: Enable and persist ip forwarding
      become: true
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: true
        reload: true

    - name: Restart wireguard and enable on boot
      become: true
      ansible.builtin.systemd:
        name: wg-quick@wg0
        enabled: true
        state: restarted

- name: Install wireguard client
  hosts: vpn_client

  tasks:
    - name: Install wireguard
      ansible.builtin.include_tasks: shared.yml

    - name: Wireguard config
      become: true
      ansible.builtin.template:
        src: templates/client.wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: "0600"
