---
- name: Install wireguard server
  hosts: vpn_server

  handlers:
    - name: reload systemctl
      become: true
      command: systemctl daemon-reload

  tasks:
    - name: Install wireguard
      ansible.builtin.include_tasks: shared.yml

    - name: Download and extract wstunnel
      become: true
      ansible.builtin.unarchive:
        src: https://github.com/erebe/wstunnel/releases/download/v10.1.10/wstunnel_10.1.10_linux_amd64.tar.gz
        dest: /usr/local/bin
        remote_src: yes
        mode: "0755"
      when: wireguard.use_tcp

    - name: Create wstunnel config
      become: true
      template: 
        src: templates/wstunnel.service.j2
        dest: /lib/systemd/system/wstunnel.service 
        mode: "0644"
      notify:
        - reload systemctl
      when: wireguard.use_tcp
        
    - name: Restart wstunnel and enable on boot
      become: true
      ansible.builtin.systemd:
        name: wstunnel
        enabled: true
        state: restarted
      when: wireguard.use_tcp

    - name: Wireguard config
      become: true
      ansible.builtin.template:
        src: templates/server.wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: "0600"

    - name: Enable and persist ip forwarding
      become: true
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        sysctl_set: true
        reload: true

    - name: Restart wireguard and enable on boot
      become: true
      ansible.builtin.systemd:
        name: wg-quick@wg0
        enabled: true
        state: restarted

- name: Install wireguard client
  hosts: vpn_client

  tasks:
    - name: Install wireguard
      ansible.builtin.include_tasks: shared.yml

    - name: Wireguard config
      become: true
      ansible.builtin.template:
        src: templates/client.wireguard.conf.j2
        dest: /etc/wireguard/wg0.conf
        owner: root
        group: root
        mode: "0600"
